apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: data-processing-source
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      # Path to maven (parent POM for multi-module build)
      context: ..
      jib: {
        args: ["-DskipTests=true"],
        project: "data-processing-source",
      }

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
     # - ../.kubernetes-manifests/**.yml
      - ./.kubernetes-manifests/**.yml
profiles:
  #  # use the cloudbuild profile to build images using Google Cloud Build
  #  - name: cloudbuild
  #    build:
  #      googleCloudBuild: {}
  #  # use the dockerfile profile to build images using Docker instead of Jib
  - name: dockerfile
    build:
      artifacts:
        - image: data-processing-source