apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-account-trigger-worker
  labels:
    app: trade-account-trigger-worker
spec:
  replicas: 1
  template:
    metadata:
      name: trade-account-trigger-worker
      labels:
        app: trade-account-trigger-worker
    spec:
      containers:
        - name: trade-account-trigger-worker
          image: trade-account-trigger-worker
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: SPRING_PROFILES_ACTIVE
            - name: KAFKA_SERVICE_HOST
              value: 'broker'
            - name: SPRING.KAFKA.BOOTSTRAP-SERVERS
              value: 'broker:9092'
            - name: MYSQL_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: velocity-db-secret
                  key: mysql-username
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velocity-db-secret
                  key: mysql-password
            - name: MYSQL_SERVICE_HOST
              value: '10.107.1.100'
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: MYSQL_SERVICE_DATABASE
              value: 'dev_global_pfac_b_enterprise_merge'
            - name: MONGO_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: velocity-db-secret
                  key: mongo-username
            - name: MONGO_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velocity-db-secret
                  key: mongo-password
            - name: MONGO_SERVICE_HOST
              value: '10.107.1.202'
            - name: REPLICASET_MONGO_SERVICE_HOST
              value: '10.107.1.202:27017'
            - name: MONGO_SERVICE_PORT
              value: '27017'
            - name: MONGO_SERVICE_DATABASE
              value: 'dev_global_pfac_b_enterprise_merge'
            - name: MONGO_SERVICE_AUTH_DATABASE
              value: 'admin'
      restartPolicy: Always
  selector:
    matchLabels:
      app: trade-account-trigger-worker
