apiVersion: v1
kind: Service
metadata:
  name: data-processing-processor
spec:
  selector:
    app: data-processing-processor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31900
  type: LoadBalancer