apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-admin-rb
subjects:
  - kind: ServiceAccount
    name: deployer-admin-sa
roleRef:
  kind: Role
  name: deployer-admin
  apiGroup: rbac.authorization.k8s.io