apiVersion: v1
kind: Secret
metadata:
  name: data-processing-db-secret
type: Opaque
stringData:
  mysql-username: 'root'
  mysql-password: 'admin'
  mongo-username: 'andrei'
  mongo-password: '28cdc6ad'